# Generated by Django 6.1 on 2026-08-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blog_id_alter_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('published', 'Published')], default='Draft', max_length=20),
        ),
    ]
